monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.usb-Kingston_HyperX_Cloud_Flight_for_PS-00.analog-stereo" }
    ]
    actions = {
      update-props = {
        channelmix.max-volume = 0.5
      }
    }
  }
]   
