[General]
Always_Use_The_Terminal=true
Aur_PackageList_Ordered_Col=4
Aur_PackageList_Sort_Order=1
Aur_Tool_Name=yay
Backend=alpm
Cache_Cleaner_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\x1\xb3\0\0\x2\xe3\0\0\x3\x83\0\0\0\0\0\0\x1\xb3\0\0\x2\xe3\0\0\x3\x83\0\0\0\x1\0\0\0\0\a\x80\0\0\0\0\0\0\x1\xb3\0\0\x2\xe3\0\0\x3\x83)
CheckUpdatesInterval=10080
Current_Tab_Index=6
Distro_RSS_Url=https://archlinux.org/feeds/news/
Enable_Internet_Checking=false
Enable_Transaction_Dialog_In_System_Upgrade=false
Instant_Search=true
Internet_Checking_Domain=www.google.com
Keep_Num_Installed=0
Keep_Num_Uninstalled=0
LastCheckUpdatesTime=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x8e\x15\x2*??\0)
Octopi_Busy_Icon_Path=
Octopi_Green_Icon_Path=
Octopi_Red_Icon_Path=
Octopi_Yellow_Icon_Path=
OptionalDeps_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\v\f\0\0\x2\xc5\0\0\a\x80\0\0\0\0\0\0\v\f\0\0\x2\xc5\0\0\0\0\0\0\0\0\a\x80\0\0\a\x80\0\0\0\0\0\0\v\f\0\0\x2\xc5)
OutputDialog_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4X\0\0\x1\xf3\0\0\0\0\0\0\0\0\0\0\x4X\0\0\x1\xf3\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x4X\0\0\x1\xf3)
PackageList_Ordered_Col=1
PackageList_Sort_Order=0
Package_Download_Size_Column_Width=120
Package_Icon_Column_Width=49
Package_Installed_Size_Column_Width=940
Package_Name_Column_Width=400
Package_Repository_Column_Width=150
Package_Version_Column_Width=260
Repo_Editor_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\x1\xb3\0\0\x3\x83\0\0\x3\\\0\0\0\0\0\0\x1\xb3\0\0\x3\x83\0\0\x3\\\0\0\0\x1\0\0\0\0\a\x80\0\0\0\0\0\0\x1\xb3\0\0\x3\x83\0\0\x3\\)
Search_Method=0
Show_Groups_Panel=false
Show_Package_Install_Reason_Column=false
Show_Package_Installed_Size_Column=true
Splitter_Horizontal_State=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1]\0\0\x1\x14\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
SyncDbInterval=10080
Transaction_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\xe3\0\0\x1\xe9\0\0\x2L\0\0\0\0\0\0\0\xe3\0\0\x1\xe9\0\0\x2L\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\xe3\0\0\x1\xe9\0\0\x2L)
Use_Default_App_Icon=true
Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\x9e\0\0\x3\x92\0\0\0\0\0\0\0\0\0\0\x4\x9e\0\0\x3\x92\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x4\x9e\0\0\x3\x92)
